---
- name: Update PHP from 5.6 to 7.4
  hosts: all
  become: true
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Remove PHP 5.6 packages
      apt:
        name:
          - php5.6
          - php5.6-fpm
          - php5.6-cli
          - php5.6-mysql
          - php5.6-gd
          - php5.6-mbstring
          - php5.6-mcrypt
        state: absent

    - name: Install PHP 7.4 packages
      apt:
        name:
          - php7.4
          - php7.4-fpm
          - php7.4-cli
          - php7.4-mysql
          - php7.4-gd
          - php7.4-mbstring
        state: present

    - name: Restart PHP-FPM
      service:
        name: php7.4-fpm
        state: restarted
